#!/usr/bin/env bash
# This script configure localhost to resolve to 127.0.0.1 and facebook.com to 8.8.8.8
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (sudo 0./change_your_home_IP)"
    exit 1
fi

HOSTS_FILE="/etc/hosts"

# Backup the original hosts
if [ ! -f "${HOSTS_FILE}.bak" ]; then
    cp "$HOSTS_FILE" "${HOSTS_FILE}.bak"
fi

sed -i '/[[:space:]]localhost$/d' "$HOSTS_FILE"
sed -i '/[[:space:]]facebook\.com$/d' "$HOSTS_FILE"

echo "127.0.0.2    localhost" >> "$HOSTS_FILE"
echo "8.8.8.8      facebook.com" >> "$HOSTS_FILE"
